### ISSUE TITLE
Removes heredoc

### ISSUE THREAD

**Issue by candyapplecorn** [erniebrodeur/ruby-beautify#42] opened 2017-08-20 21:33 UTC
Removed my heredoc's contents. I used the ~ form for my heredoc like so:

```ruby
print <<~HEREDOC

				The dependancy 'youtube_dl' is not installed.
				To install this program, see 
				https://rg3.github.io/youtube-dl/download.html

				Are you using OSX or Linux and would like to
				install youtube_dl automatically? 
		HEREDOC
```

**Comment by erniebrodeur** [comment] 2018-09-09 08:05
Dupe of #30

**Closed** 2018-09-09 08:05 UTC
Labels: bug, duplicate
